### PR TITLE
Add fedora uri to index

### PR DESCRIPTION
**Pull request by gravesm**

### CODE REVIEW

**Comment by richardrodgers** [comment]
Not an observation about the code - but a question about our design. Since the Fedora service is not directly exposed to clients, I'm guessing we are not planning to bind a DNS name to it. If that is the case, resource URIs will be not persistent (eg. http://IP:8080/fcrepo/rest/theses/....) where 'IP' is a runtime kubernetes assignment that might not repeat on a redploy..... What do you think?

**Comment by gravesm** [comment]
I can replace the IP with the value of the FEDORA_SERVICE_HOST env var when I add the resource to the index. That's about as close as we're going to get to stable without DNS.

**Comment by richardrodgers** [comment]
I was actually thinking of going the other way: ignoring the server completely and having the Fedora ID be:
1721.1-42469 (which is just a transformation of the handle: 1721.1/42469) - we can guarantee that these will be unique. Let's leave it as is in the PR for now (API server can parse the URI if it wants to) I can reliably resolve those short IDs since kubernetes will furnish me with an ENV var to the server...

**Comment by gravesm** [comment]
Cool, I'll add an issue to revisit this.

**Pull request merged**
